dist: xenial
language: cpp
compiler:
- gcc
script: ./travis.sh
matrix:
  include:
  - os: linux
  addons:
    apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - g++-7.3
    env:
    - MATRIX_EVAL="CC=gcc-7.3 && CXX=g++-7.3"
